version: "3.8"

services:
  docker-mysql:
    image: mariadb:10.5.8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=state-machine
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - docker-mysql
    build:
      context: ./
      dockerfile: Dockerfile
#    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/state-machine?createDatabaseIfNotExist-true&autoReconnect=true&useSSL=false
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
